### 登录
POST http://localhost:11031/tianxuan-auth/admin/login
Content-Type: application/json

{
  "username": "admin",
  "password": "111111"
}

### 获取admin用户信息

GET http://localhost:11031/tianxuan-user/adminInfo/myInfo
Headerusertoken: admin@eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XCJpZFwiOlwiMTAwMVwiLFwidXNlcm5hbWVcIjpcImFkbWluXCIsXCJwYXNzd29yZFwiOlwiNjJkMDlmN2VjNTg5MDE0NDA3ODA5Mzg3ZjM0MjQ1NmJcIixcInNsYXRcIjpcIjgxMTFcIixcInJlbWFya1wiOlwi566h55CG5ZGYXCIsXCJmYWNlXCI6XCJodHRwOi8vaGlyZS50Lm11a2V3YW5nLmNvbS9zdGF0aWMvYWRtaW5GYWNlLzY0NDg0MmUzLTAxNzMtNDJjMC1hN2E5LWFiZGJhMDljMzU4Yi5wbmdcIixcImNyZWF0ZVRpbWVcIjoxNjU0ODMwMjA5MDAwLFwidXBkYXRlZFRpbWVcIjoxNjYwODgwNjcyMDAwfSJ9.tTjCYhRqSONDOjAN_6F4YbPCcIVysaOEIWz5sH39trw

### hello1
GET http://localhost:11031/tianxuan-auth/admin/hello

### hello2
GET http://localhost:11031/tianxuan-auth/admin/hello2

### counts
POST http://localhost:11031/tianxuan-resource/sysParam/counts
Headerusertoken: admin@eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ7XCJpZFwiOlwiMTAwMVwiLFwidXNlcm5hbWVcIjpcImFkbWluXCIsXCJwYXNzd29yZFwiOlwiNjJkMDlmN2VjNTg5MDE0NDA3ODA5Mzg3ZjM0MjQ1NmJcIixcInNsYXRcIjpcIjgxMTFcIixcInJlbWFya1wiOlwi566h55CG5ZGYXCIsXCJmYWNlXCI6XCJodHRwOi8vaGlyZS50Lm11a2V3YW5nLmNvbS9zdGF0aWMvYWRtaW5GYWNlLzY0NDg0MmUzLTAxNzMtNDJjMC1hN2E5LWFiZGJhMDljMzU4Yi5wbmdcIixcImNyZWF0ZVRpbWVcIjoxNjU0ODMwMjA5MDAwLFwidXBkYXRlZFRpbWVcIjoxNjYwODgwNjcyMDAwfSJ9.tTjCYhRqSONDOjAN_6F4YbPCcIVysaOEIWz5sH39trw
