server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1
  # 默认端口号设置
  port: ${PORT:11071}



jasypt:
  encryptor:
    # 加密算法
    algorithm: PBEWithMD5AndDES
    # 加密的秘钥(盐)
    password: wuyiccc