server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1
  # 默认端口号设置
  port: ${PORT:11011}
spring:
  application:
    name: tianxuan-user

# 配置日志级别
logging:
  level:
    root: info

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      # 雪花算法id
      id-type: assign_id
    # 去掉mybatis-plus banner图片
    banner: false

jasypt:
  encryptor:
    # 加密算法
    algorithm: PBEWithMD5AndDES
    # 加密的秘钥(盐)
    password: wuyiccc